# Generated by Django 5.1.6 on 2025-10-15 07:59

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(choices=[('FREE', 'Free'), ('BASIC', 'Basic'), ('ENTERPRISE', 'Enterprise')], max_length=50, unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_rooms', models.PositiveIntegerField(default=5)),
                ('allow_logo_upload', models.BooleanField(default=False)),
                ('access_to_analytics', models.BooleanField(default=False)),
                ('priority_support', models.BooleanField(default=False)),
                ('promotional_visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Hotel Email'),
        ),
        migrations.CreateModel(
            name='HotelSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_renew', models.BooleanField(default=False)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='registration.hotel')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registration.subscriptionplan')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
